name: codecv
# Start with the lamp recipe
recipe: lemp
config:
  php: '7.4'
  via: nginx
  composer_version: '2.0.7'
services:
  node:
    type: node:16
    ssl: 3000
    scanner: false
  appserver:
    type: php
tooling:
  setup:
    cmd:
      - appserver: cd php && composer install --no-cache
      - node: npm install
      - appserver: cd php && php -r "file_exists('.env') || copy('.env.example', '.env');"
  npm:
    service: node
    user: root
